#!/bin/bash

memory="1G"
iso="windows.iso"
enable_graphics="no"
image="windows10.qcow2"
graphics_arg="-nographics"
cores=1
virtio_img="virtio-win-0.1.189.iso"
vm_name="ls4w"
ovmf_vars="/usr/share/OVMF/OVMF_VARS.fd"
ovmf_code="/usr/share/OVMF/OVMF_CODE.fd"

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
	-m|--memory)
	memory="$2"
	shift
	shift
	;;

	-i|--iso)
	iso="$2"
	shift
	shift
	;;

	-g|--enable-graphics)
	enable_graphics="$2"
	shift
	shift
	;;

	-h|--hdd-image)
	image="$2"
	shift
	shift
	;;

	-i|--cores)
	cores="$2"
	shift
	shift
	;;
	
	-v|--virtio)
	virtio_img="$2"
	shift
	shift
	;;

	-n|--name)
	vm_name="$2"
	shift
	shift
	;;

	-o|--ovmf-code)
	ovmf_code="$2"
	shift
	shift
	;;

	-p|--ovmf-vars)
	ovmf_vars="$2"
	shift
	shift
	;;

esac
done

if [ "$enable_graphics" = "yes" ]; then
	graphics_arg="-vga qxl"
else
	graphics_arg="-nographic"
fi

cp $ovmf_vars $image.fd


echo "Starting VM from $image. Memory: $memory, Graphics argument: $graphics_arg, booting with: $iso"
qemu-system-x86_64 \
-name guest=$vm_name,debug-threads=on \
-drive if=pflash,format=raw,readonly,file=$ovmf_code \
-drive if=pflash,format=raw,file=$image.fd \
-m $memory \
-smp $cores \
-machine type=q35,accel=kvm \
-no-reboot \
$graphics_arg \
-rtc base=localtime,driftfix=slew \
-global kvm-pit.lost_tick_policy=delay \
-global ICH9-LPC.disable_s3=1 \
-global ICH9-LPC.disable_s4=1 \
-boot strict=on \
-blockdev "{\"driver\":\"file\",\"filename\":\"$image\",\"node-name\":\"libvirt-2-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}" \
-blockdev '{"node-name":"libvirt-2-format","read-only":false,"driver":"qcow2","file":"libvirt-2-storage","backing":null}' \
-device ide-hd,bus=ide.0,drive=libvirt-2-format,id=sata0-0-0,bootindex=1 \
# -blockdev "{\"driver\":\"file\",\"filename\":\"$iso\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\"}" \
# -blockdev '{"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"}' \
# -device ide-cd,bus=ide.1,drive=libvirt-1-format,id=sata0-0-1,bootindex=2 \

